03:17:47:| 'HOME'
Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 265, in my_event_handler
    print(os.environ['HOME'])
  File "C:\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'


03:19:08:| 'lachs_binance_key'
Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 264, in my_event_handler
    print(os.environ['lachs_binance_key'])
  File "C:\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'lachs_binance_key'


03:36:54:| 'lachs_binance_key'
Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 265, in my_event_handler
    print(os.environ['lachs_binance_key'])
  File "C:\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'lachs_binance_key'


03:38:20:| 'LACHS_BINANCE_KEY'
Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 267, in my_event_handler
    print(os.environ['LACHS_BINANCE_KEY'])
  File "C:\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'LACHS_BINANCE_KEY'


03:42:27:| 'LACHS_BINANCE_KEY'
Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 267, in my_event_handler
    print(os.environ['LACHS_BINANCE_KEY'])
  File "C:\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'LACHS_BINANCE_KEY'


03:44:53:| 'LACHS_BINANCE_KEY'
Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 267, in my_event_handler
    print(os.environ['LACHS_BINANCE_KEY'])
  File "C:\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'LACHS_BINANCE_KEY'


03:46:31:| 'LACHS_BINANCE_SECRET'
Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 268, in my_event_handler
    print(os.environ['LACHS_BINANCE_SECRET'])
  File "C:\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'LACHS_BINANCE_SECRET'


03:50:04:| 'LACHS_BINANCE_KEY'
Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 267, in my_event_handler
    print(os.environ['LACHS_BINANCE_KEY'])
  File "C:\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'LACHS_BINANCE_KEY'


03:51:22:| 'LACHS_BINANCE_KEY'
Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 267, in my_event_handler
    print(os.environ['LACHS_BINANCE_KEY'])
  File "C:\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'LACHS_BINANCE_KEY'


03:52:20:| 'LACHS_BINANCE_KEY'
Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 267, in my_event_handler
    print(os.environ['LACHS_BINANCE_KEY'])
  File "C:\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'LACHS_BINANCE_KEY'


15:25:41:| 'VAR_ENV'
Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 266, in my_event_handler
    print(os.environ['VAR_ENV'])
  File "C:\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'VAR_ENV'


15:30:41:| 'VAR_ENV'
Traceback (most recent call last):
  File "C:\Users\lachl\Documents\GitHub\telebagger\telebagger.py", line 266, in my_event_handler
    print(os.environ['VAR_ENV'])
  File "C:\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'VAR_ENV'


